import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const { studentName, usn, semester, subjects, result } = await req.json()

    if (!usn || !subjects) {
      throw new Error('Missing usn or subjects data')
    }

    let subjectsContext = ''
    if (Array.isArray(subjects)) {
      subjectsContext = subjects.map((s: any) => 
        `${s.code} - ${s.name}: Internal=${s.internal ?? '-'}, External=${s.external ?? '-'}, Total=${s.total ?? '-'}, Status=${s.passed ? 'PASS' : 'FAIL'}`
      ).join('\n')
    }

    const systemPrompt = `You are an expert Academic Advisor AI at EduPredict. Generate a professional and insightful academic summary based on the student's VTU university results.
Your tone should be constructive, professional, and tailored to help the student and mentor understand the performance.
If the student has failed subjects, provide encouraging but firm advice on focusing on those areas.
If the student has done well, praise their efforts and encourage maintaining consistency.

Do not use overly complex vocabulary. Write in clear paragraphs. Do NOT output markdown formatting like bold (**), headers (#), or lists (-) unless necessary. Just plain readable text is preferred, or very light formatting.

Keep the summary to 2-3 concise paragraphs (under 150 words total if possible).`

    const userPrompt = `
Academic Data Context:
Name: ${studentName || 'Unknown Student'}
USN: ${usn}
Semester(s): ${semester}
Overall Result for this context: ${result}

*** Subjects and Marks ***
${subjectsContext}

Please generate the summary now.
`

    const openaiRes = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${Deno.env.get('OPENAI_API_KEY')}`,
      },
      body: JSON.stringify({
        model: 'gpt-4o',
        temperature: 0.5,
        messages: [
           { role: 'system', content: systemPrompt },
           { role: 'user', content: userPrompt }
        ]
      })
    })

    if (!openaiRes.ok) {
       const tx = await openaiRes.text()
       throw new Error(`OpenAI Request Failed: ${tx}`)
    }

    const openaiData = await openaiRes.json()
    const summary = openaiData.choices?.[0]?.message?.content?.trim()
    
    if (!summary) {
       throw new Error('No content generated by AI')
    }

    return new Response(JSON.stringify({ ok: true, summary }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    })

  } catch (error: any) {
    return new Response(
      JSON.stringify({ ok: false, error: error.message }),
      { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }
})
